export const studioAssets = {
  backgrounds: {
    lobby: '/assets/studio/backgrounds/casino-lobby.png',
    lounge: '/assets/studio/backgrounds/casino-lounge.png',
    control: '/assets/studio/backgrounds/control-room.png'
  },
  iconSheet: '/assets/studio/sheets/icon-sheet.png',
  icons: {
    home: '/assets/studio/icons/home.png',
    profile: '/assets/studio/icons/profile.png',
    login: '/assets/studio/icons/login.png',
    register: '/assets/studio/icons/register.png',
    phone: '/assets/studio/icons/phone.png',
    lock: '/assets/studio/icons/lock.png',
    wallet: '/assets/studio/icons/wallet.png',
    deposit: '/assets/studio/icons/deposit.png',
    withdraw: '/assets/studio/icons/withdraw.png',
    transfer: '/assets/studio/icons/transfer.png',
    history: '/assets/studio/icons/history.png',
    shop: '/assets/studio/icons/shop.png',
    backpack: '/assets/studio/icons/backpack.png',
    vip: '/assets/studio/icons/vip.png',
    slots: '/assets/studio/icons/slots.png',
    blackjack: '/assets/studio/icons/blackjack.png',
    roulette: '/assets/studio/icons/roulette.png',
    poker: '/assets/studio/icons/poker.png',
    bingo: '/assets/studio/icons/bingo.png',
    dice: '/assets/studio/icons/dice.png',
    chat: '/assets/studio/icons/chat.png',
    friends: '/assets/studio/icons/friends.png',
    clan: '/assets/studio/icons/clan.png',
    map: '/assets/studio/icons/map.png',
    travel: '/assets/studio/icons/travel.png',
    marriage: '/assets/studio/icons/marriage.png',
    trophy: '/assets/studio/icons/trophy.png',
    ranking: '/assets/studio/icons/ranking.png',
    security: '/assets/studio/icons/security.png',
    settings: '/assets/studio/icons/settings.png',
    notifications: '/assets/studio/icons/notifications.png',
    radio: '/assets/studio/icons/radio.png',
    live: '/assets/studio/icons/live.png',
    maintenance: '/assets/studio/icons/maintenance.png',
    adminLock: '/assets/studio/icons/admin-lock.png',
    gift: '/assets/studio/icons/gift.png'
  }
} as const;
