-- ============================================================
-- BLINDERS V6 — ADMIN FORMS + CAROUSEL + ACTIONS
--
-- Corrige:
-- - Admin não fica preso em tela genérica;
-- - app_admin_execute_action executa ações por módulo;
-- - mantém validação por token/cargo;
-- - mantém logs em admin_audit_logs;
-- - inclui funções para criar conta, aprovar, suspender,
--   configs, anúncio, loja, bônus e banco.
--
-- Resultado esperado:
-- BLINDERS_NETLIFY_V6_ADMIN_FORMS_CAROUSEL_OK
-- ============================================================

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

-- -----------------------------
-- Base
-- -----------------------------
create table if not exists public.app_members (
  id uuid primary key default extensions.gen_random_uuid()
);

alter table public.app_members add column if not exists nick text;
alter table public.app_members add column if not exists zarcovi_account text;
alter table public.app_members add column if not exists password_hash text;
alter table public.app_members add column if not exists role text default 'user';
alter table public.app_members add column if not exists status text default 'pending';
alter table public.app_members add column if not exists iris_member_id text;
alter table public.app_members add column if not exists balance_virtual_units numeric(40,2) not null default 0;
alter table public.app_members add column if not exists friend_code text;
alter table public.app_members add column if not exists created_at timestamptz default now();
alter table public.app_members add column if not exists updated_at timestamptz default now();

create index if not exists ix_v6_members_nick_lower on public.app_members(lower(nick));
create index if not exists ix_v6_members_status on public.app_members(status);

create table if not exists public.app_member_sessions (
  id uuid primary key default extensions.gen_random_uuid()
);

alter table public.app_member_sessions add column if not exists member_id uuid;
alter table public.app_member_sessions add column if not exists token text;
alter table public.app_member_sessions add column if not exists expires_at timestamptz default now()+interval '30 days';
alter table public.app_member_sessions add column if not exists created_at timestamptz default now();

create index if not exists ix_v6_sessions_token on public.app_member_sessions(token);

drop function if exists public.v25_parse(text);
create or replace function public.v25_parse(p_amount text)
returns numeric language plpgsql immutable as $$
declare s text := upper(trim(coalesce(p_amount,''))); n numeric;
begin
  if s='' then return 0; end if;
  s := replace(replace(s,' ',''),',','.');
  if s like '%T' then
    n := nullif(regexp_replace(s,'[^0-9.\-]','','g'),'')::numeric;
    return greatest(n,0)*1000000000000;
  end if;
  if s like '%B' then
    n := nullif(regexp_replace(s,'[^0-9.\-]','','g'),'')::numeric;
    return greatest(n,0)*1000000000;
  end if;
  n := nullif(regexp_replace(s,'[^0-9.\-]','','g'),'')::numeric;
  return greatest(n,0);
exception when others then
  raise exception 'Valor inválido. Use 1B, 1500B, 1.5T ou 3T.';
end;
$$;

drop function if exists public.v25_format(numeric);
create or replace function public.v25_format(p_units numeric)
returns text language plpgsql immutable as $$
declare v numeric := coalesce(p_units,0);
begin
  if abs(v)>=1000000000000 then return trim(to_char(v/1000000000000,'FM999999999999990D00'))||'T'; end if;
  if abs(v)>=1000000000 then return trim(to_char(v/1000000000,'FM999999999999990D00'))||'B'; end if;
  return trim(to_char(v,'FM999999999999990D00'));
end;
$$;

drop function if exists public.v25_current(text);
create or replace function public.v25_current(p_token text)
returns public.app_members
language plpgsql
security definer
set search_path=public,extensions
as $$
declare m public.app_members;
begin
  select a.*
  into m
  from public.app_member_sessions s
  join public.app_members a on a.id=s.member_id
  where s.token=p_token
    and s.expires_at>now()
  limit 1;

  if m.id is null then
    raise exception 'Sessão expirada. Entre novamente.';
  end if;

  return m;
end;
$$;

drop function if exists public.app_assert_admin(text);
create or replace function public.app_assert_admin(p_token text)
returns public.app_members
language plpgsql
security definer
set search_path=public,extensions
as $$
declare m public.app_members;
begin
  m := public.v25_current(p_token);

  if coalesce(m.role,'user') not in ('admin','owner') then
    raise exception 'Acesso reservado para admin/dono.';
  end if;

  return m;
end;
$$;

-- -----------------------------
-- Logs e bancos
-- -----------------------------
create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  admin_id uuid,
  action text not null,
  target text,
  payload jsonb not null default '{}',
  result jsonb not null default '{}',
  created_at timestamptz default now()
);

create table if not exists public.iris_bank_accounts_mod020 (
  bank_key text primary key,
  display_name text not null,
  iris_id text not null unique,
  balance_units numeric(40,2) not null default 0,
  deposits_total_units numeric(40,2) not null default 0,
  table_fee_units numeric(40,2) not null default 0,
  solo_profit_units numeric(40,2) not null default 0,
  reserve_percent numeric(8,2) not null default 10,
  max_single_prize_percent numeric(8,2) not null default 10,
  status text not null default 'active',
  updated_at timestamptz default now()
);

insert into public.iris_bank_accounts_mod020(bank_key,display_name,iris_id,balance_units)
values('EMSHBY','Banco EMSHBY','EMSHBY',100000000000000)
on conflict(bank_key) do update set status='active', updated_at=now();

-- -----------------------------
-- Settings / anúncios / loja / bônus
-- -----------------------------
create table if not exists public.system_settings (
  key text primary key,
  value jsonb not null default '{}',
  updated_at timestamptz default now()
);

create table if not exists public.harmony_announcements (
  id uuid primary key default extensions.gen_random_uuid(),
  title text,
  message text not null,
  icon text default '📢',
  active boolean not null default true,
  priority int not null default 100,
  starts_at timestamptz default now(),
  ends_at timestamptz,
  created_at timestamptz default now()
);

create table if not exists public.shop_items (
  item_key text
);

alter table public.shop_items add column if not exists id uuid;
update public.shop_items set id = extensions.gen_random_uuid() where id is null;
alter table public.shop_items alter column id set default extensions.gen_random_uuid();
alter table public.shop_items add column if not exists title text;
alter table public.shop_items add column if not exists name text;
alter table public.shop_items add column if not exists category text default 'profile';
alter table public.shop_items add column if not exists description text;
alter table public.shop_items add column if not exists item_type text default 'badge';
alter table public.shop_items add column if not exists rarity text default 'common';
alter table public.shop_items add column if not exists price_units numeric(40,2) not null default 0;
alter table public.shop_items add column if not exists price numeric(40,2) default 0;
alter table public.shop_items add column if not exists stock_limit int;
alter table public.shop_items add column if not exists stock int default 0;
alter table public.shop_items add column if not exists active boolean not null default true;
alter table public.shop_items add column if not exists metadata jsonb not null default '{}';
alter table public.shop_items add column if not exists data jsonb not null default '{}';
alter table public.shop_items add column if not exists created_at timestamptz default now();
alter table public.shop_items add column if not exists updated_at timestamptz default now();

update public.shop_items
set category = coalesce(nullif(category,''),'profile'),
    item_type = coalesce(nullif(item_type,''),'badge'),
    title = coalesce(nullif(title,''), nullif(name,''), item_key, 'Item'),
    name = coalesce(nullif(name,''), nullif(title,''), item_key, 'Item'),
    price_units = coalesce(price_units, price, 0),
    price = coalesce(price, price_units, 0),
    metadata = coalesce(metadata, data, '{}'::jsonb),
    data = coalesce(data, metadata, '{}'::jsonb);

create table if not exists public.bonus_codes (
  id uuid primary key default extensions.gen_random_uuid(),
  code text not null unique,
  title text,
  money_units numeric(40,2) default 0,
  item_key text,
  max_uses int,
  max_per_user int default 1,
  active boolean not null default true,
  expires_at timestamptz,
  metadata jsonb not null default '{}',
  created_at timestamptz default now()
);

-- -----------------------------
-- Execução admin real
-- -----------------------------
drop function if exists public.app_admin_execute_action(text,text,text,jsonb);
create or replace function public.app_admin_execute_action(
  p_token text,
  p_module text,
  p_action text,
  p_payload jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=public,extensions
as $$
declare
  admin public.app_members;
  result jsonb := '{}'::jsonb;
  target text := coalesce(p_payload->>'target', p_payload->>'nick', p_payload->>'code', p_payload->>'item_key', '');
  amount numeric := 0;
  new_id uuid;
  clean_nick text;
  login_nick text;
  role_value text;
  status_value text;
begin
  admin := public.app_assert_admin(p_token);

  -- Criar conta
  if p_module='accounts' and p_action='create' then
    clean_nick := trim(coalesce(p_payload->>'nick',''));
    if clean_nick='' then raise exception 'Informe o nick da conta.'; end if;

    -- admin@(nome) vira admin, mas login usa só nome
    if lower(clean_nick) like 'admin@%' then
      clean_nick := substr(clean_nick, 7);
      role_value := 'admin';
    else
      role_value := coalesce(nullif(p_payload->>'role',''),'user');
    end if;

    login_nick := clean_nick;
    status_value := coalesce(nullif(p_payload->>'status',''),'active');
    amount := public.v25_parse(coalesce(p_payload->>'balance','0'));

    if exists(select 1 from public.app_members where lower(nick)=lower(login_nick)) then
      raise exception 'Já existe uma conta com esse nick.';
    end if;

    insert into public.app_members(
      nick,zarcovi_account,password_hash,role,status,iris_member_id,balance_virtual_units,friend_code,created_at,updated_at
    )
    values(
      login_nick,
      nullif(p_payload->>'zarcovi_account',''),
      extensions.crypt(coalesce(nullif(p_payload->>'password',''),'1234'), extensions.gen_salt('bf')),
      role_value,
      status_value,
      coalesce(nullif(p_payload->>'zarcovi_account',''), 'IRIS-'||upper(substr(encode(extensions.gen_random_bytes(5),'hex'),1,10))),
      amount,
      'FR-'||upper(substr(encode(extensions.gen_random_bytes(5),'hex'),1,10)),
      now(),
      now()
    )
    returning id into new_id;

    result := jsonb_build_object('ok',true,'message','Conta criada.','memberId',new_id,'nick',login_nick,'role',role_value,'status',status_value,'balanceLabel',public.v25_format(amount));

  -- Aprovar / status conta
  elsif p_module='accounts' and p_action in ('approve','delete','role') then
    if target='' then raise exception 'Informe nick ou ID da conta.'; end if;

    if p_action='approve' then
      status_value := coalesce(nullif(p_payload->>'status',''),'active');
      update public.app_members
      set status=status_value, updated_at=now()
      where lower(nick)=lower(target) or id::text=target;
      result := jsonb_build_object('ok',true,'message','Status da conta atualizado.','target',target,'status',status_value);

    elsif p_action='delete' then
      status_value := case coalesce(p_payload->>'account_action','suspend')
        when 'reactivate' then 'active'
        when 'delete' then 'deleted'
        else 'suspended'
      end;
      update public.app_members
      set status=status_value, updated_at=now()
      where lower(nick)=lower(target) or id::text=target;
      result := jsonb_build_object('ok',true,'message','Conta atualizada.','target',target,'status',status_value);

    elsif p_action='role' then
      role_value := coalesce(nullif(p_payload->>'role',''),'user');
      update public.app_members
      set role=role_value, updated_at=now()
      where lower(nick)=lower(target) or id::text=target;
      result := jsonb_build_object('ok',true,'message','Cargo atualizado.','target',target,'role',role_value);
    end if;

  -- Buscar contas
  elsif p_module='accounts' and p_action='search' then
    result := (
      select jsonb_build_object(
        'ok',true,
        'message','Busca de contas concluída.',
        'items', coalesce(jsonb_agg(jsonb_build_object(
          'nick',m.nick,'role',m.role,'status',m.status,'balance',public.v25_format(m.balance_virtual_units),'iris',m.iris_member_id
        ) order by m.created_at desc),'[]'::jsonb)
      )
      from (
        select *
        from public.app_members
        where
          coalesce(p_payload->>'query','')=''
          or lower(nick) like '%'||lower(p_payload->>'query')||'%'
          or lower(role) like '%'||lower(p_payload->>'query')||'%'
          or id::text = p_payload->>'query'
        limit 20
      ) m
    );

  -- Banco: depósito
  elsif p_module='bank' and p_action='deposit' then
    amount := public.v25_parse(coalesce(p_payload->>'amount','0'));
    if amount<=0 then raise exception 'Informe um valor de depósito maior que zero.'; end if;

    update public.iris_bank_accounts_mod020
    set balance_units=balance_units+amount,
        deposits_total_units=deposits_total_units+amount,
        updated_at=now()
    where bank_key='EMSHBY';

    result := jsonb_build_object('ok',true,'message','Depósito registrado no EMSHBY.','code',coalesce(p_payload->>'code',''),'amountLabel',public.v25_format(amount));

  -- Banco: saque
  elsif p_module='bank' and p_action='withdraw' then
    result := jsonb_build_object('ok',true,'message','Saque marcado como conferido.','code',coalesce(p_payload->>'code',''));

  -- Banco: cofre/iris
  elsif p_module='bank' and p_action in ('vault','iris','transfer-audit') then
    amount := public.v25_parse(coalesce(p_payload->>'amount','0'));
    if p_action='vault' and coalesce(p_payload->>'vault_action','consult')='set-balance' then
      update public.iris_bank_accounts_mod020 set balance_units=amount, updated_at=now() where bank_key='EMSHBY';
    elsif p_action='vault' and coalesce(p_payload->>'vault_action','consult')='add-balance' then
      update public.iris_bank_accounts_mod020 set balance_units=balance_units+amount, updated_at=now() where bank_key='EMSHBY';
    elsif p_action='vault' and coalesce(p_payload->>'vault_action','consult')='remove-balance' then
      update public.iris_bank_accounts_mod020 set balance_units=greatest(balance_units-amount,0), updated_at=now() where bank_key='EMSHBY';
    end if;

    if p_payload ? 'reserve_percent' then
      update public.iris_bank_accounts_mod020
      set reserve_percent=coalesce(nullif(p_payload->>'reserve_percent','')::numeric,reserve_percent),
          max_single_prize_percent=coalesce(nullif(p_payload->>'max_prize_percent','')::numeric,max_single_prize_percent),
          updated_at=now()
      where bank_key='EMSHBY';
    end if;

    result := jsonb_build_object('ok',true,'message','Ação do Banco IRIS registrada.','module',p_action);

  -- Jogos
  elsif p_module='games' then
    if p_action='rules' then
      insert into public.unified_game_rules(game_key,game_name,rule_text,min_bet_units,max_bet_units,active,updated_at)
      values(
        coalesce(nullif(p_payload->>'game_key',''),'unknown'),
        coalesce(nullif(p_payload->>'game_key',''),'unknown'),
        coalesce(nullif(p_payload->>'rule_text',''),'Regra atualizada pelo Admin.'),
        public.v25_parse(coalesce(p_payload->>'min_bet','0')),
        nullif(public.v25_parse(coalesce(p_payload->>'max_bet','0')),0),
        coalesce(p_payload->>'active','true')='true',
        now()
      )
      on conflict(game_key) do update set
        rule_text=excluded.rule_text,
        min_bet_units=excluded.min_bet_units,
        max_bet_units=excluded.max_bet_units,
        active=excluded.active,
        updated_at=now();
    end if;
    result := jsonb_build_object('ok',true,'message','Ação de jogos registrada.','action',p_action);

  -- Bônus / eventos
  elsif p_module='bonus' then
    if p_action='create' then
      insert into public.bonus_codes(code,title,money_units,item_key,max_uses,max_per_user,active,expires_at,metadata)
      values(
        upper(trim(coalesce(p_payload->>'code',''))),
        p_payload->>'title',
        public.v25_parse(coalesce(p_payload->>'money','0')),
        nullif(p_payload->>'item_key',''),
        nullif(p_payload->>'max_uses','')::int,
        coalesce(nullif(p_payload->>'max_per_user','')::int,1),
        true,
        nullif(p_payload->>'expires_at','')::timestamptz,
        p_payload
      )
      on conflict(code) do update set
        title=excluded.title,
        money_units=excluded.money_units,
        item_key=excluded.item_key,
        max_uses=excluded.max_uses,
        max_per_user=excluded.max_per_user,
        active=true,
        expires_at=excluded.expires_at,
        metadata=excluded.metadata;
    end if;
    result := jsonb_build_object('ok',true,'message','Bônus/evento registrado.','action',p_action);

  -- Loja
  elsif p_module='shop' then
    if p_action='save' then
      insert into public.shop_items(item_key,title,name,category,description,item_type,rarity,price_units,price,stock,active,metadata,data,created_at,updated_at)
      select
        p_payload->>'item_key',
        p_payload->>'title',
        p_payload->>'title',
        coalesce(nullif(p_payload->>'category',''),'profile'),
        coalesce(p_payload->>'description',''),
        coalesce(nullif(p_payload->>'item_type',''),'badge'),
        coalesce(nullif(p_payload->>'rarity',''),'common'),
        public.v25_parse(coalesce(p_payload->>'price','0')),
        public.v25_parse(coalesce(p_payload->>'price','0')),
        coalesce(nullif(p_payload->>'stock','')::int,0),
        coalesce(p_payload->>'active','true')='true',
        p_payload,
        p_payload,
        now(),
        now()
      where not exists (select 1 from public.shop_items where item_key=p_payload->>'item_key');

      update public.shop_items
      set title=p_payload->>'title',
          name=p_payload->>'title',
          category=coalesce(nullif(p_payload->>'category',''),'profile'),
          item_type=coalesce(nullif(p_payload->>'item_type',''),'badge'),
          rarity=coalesce(nullif(p_payload->>'rarity',''),'common'),
          price_units=public.v25_parse(coalesce(p_payload->>'price','0')),
          price=public.v25_parse(coalesce(p_payload->>'price','0')),
          stock=coalesce(nullif(p_payload->>'stock','')::int,0),
          active=coalesce(p_payload->>'active','true')='true',
          metadata=p_payload,
          data=p_payload,
          updated_at=now()
      where item_key=p_payload->>'item_key';
    end if;
    result := jsonb_build_object('ok',true,'message','Loja/inventário atualizado.','action',p_action);

  -- Anúncios / settings / sistema
  elsif p_module='system' then
    if p_action='announcement' then
      insert into public.harmony_announcements(message,icon,active,priority,created_at)
      values(
        coalesce(nullif(p_payload->>'message',''),'Novo aviso do servidor.'),
        '📢',
        coalesce(p_payload->>'active','true')='true',
        coalesce(nullif(p_payload->>'priority','')::int,100),
        now()
      );
      result := jsonb_build_object('ok',true,'message','Anúncio publicado.');
    elsif p_action in ('settings','maintenance') then
      insert into public.system_settings(key,value,updated_at)
      values(
        coalesce(nullif(p_payload->>'setting',''), case when p_action='maintenance' then 'maintenance' else 'general' end),
        p_payload,
        now()
      )
      on conflict(key) do update set value=excluded.value, updated_at=now();
      result := jsonb_build_object('ok',true,'message','Configuração salva.');
    else
      result := jsonb_build_object('ok',true,'message','Ação de sistema registrada.','action',p_action);
    end if;

  -- Outros módulos
  else
    result := jsonb_build_object('ok',true,'message','Ação registrada para módulo futuro.','module',p_module,'action',p_action);
  end if;

  insert into public.admin_audit_logs(admin_id,action,target,payload,result)
  values(admin.id, p_module||':'||p_action, target, coalesce(p_payload,'{}'::jsonb), result);

  return result || jsonb_build_object('admin',admin.nick,'at',now());
end;
$$;

-- Compatibilidade com functions antigas
drop function if exists public.app_admin_secure_action(text,text,jsonb);
create or replace function public.app_admin_secure_action(p_token text, p_action text, p_payload jsonb default '{}'::jsonb)
returns jsonb
language plpgsql
security definer
set search_path=public,extensions
as $$
begin
  return public.app_admin_execute_action(p_token, split_part(coalesce(p_action,'system:log'),':',1), split_part(coalesce(p_action,'system:log'),':',2), p_payload);
end;
$$;

drop function if exists public.app_admin_confirm_deposit(text,text,text,text);
create or replace function public.app_admin_confirm_deposit(p_token text, p_code text, p_amount text, p_note text default '')
returns jsonb
language plpgsql
security definer
set search_path=public,extensions
as $$
begin
  return public.app_admin_execute_action(
    p_token,
    'bank',
    'deposit',
    jsonb_build_object('code',p_code,'amount',p_amount,'note',p_note)
  );
end;
$$;

drop function if exists public.app_admin_confirm_withdraw(text,text,text);
create or replace function public.app_admin_confirm_withdraw(p_token text, p_code text, p_note text default '')
returns jsonb
language plpgsql
security definer
set search_path=public,extensions
as $$
begin
  return public.app_admin_execute_action(
    p_token,
    'bank',
    'withdraw',
    jsonb_build_object('code',p_code,'note',p_note)
  );
end;
$$;

grant execute on function public.app_admin_execute_action(text,text,text,jsonb) to anon, authenticated;
grant execute on function public.app_admin_secure_action(text,text,jsonb) to anon, authenticated;
grant execute on function public.app_admin_confirm_deposit(text,text,text,text) to anon, authenticated;
grant execute on function public.app_admin_confirm_withdraw(text,text,text) to anon, authenticated;
grant execute on function public.v25_current(text) to anon, authenticated;
grant execute on function public.app_assert_admin(text) to anon, authenticated;
grant execute on function public.v25_parse(text) to anon, authenticated;
grant execute on function public.v25_format(numeric) to anon, authenticated;

notify pgrst, 'reload schema';

select 'BLINDERS_NETLIFY_V6_ADMIN_FORMS_CAROUSEL_OK' as status;
