-- ============================================================
-- BLINDERS RELEASE V4 — AUTH / LOGIN / PWA SQL
-- Rode depois do SQL V2.
-- Resultado esperado: BLINDERS_RELEASE_V4_AUTH_SQL_OK
-- ============================================================
create extension if not exists pgcrypto;
alter table public.blinders_members add column if not exists password_hash text, add column if not exists password_repaired_at timestamptz, add column if not exists phone_verified boolean not null default false;
update public.blinders_members set password_hash = crypt('admin123', gen_salt('bf')) where lower(nick)=lower('KageShinobi') and (password_hash is null or password_hash='');
drop function if exists public.app_phone_valid(text); drop function if exists public.app_session_payload(uuid,text); drop function if exists public.app_login(text,text); drop function if exists public.app_register(text,text,text,text); drop function if exists public.app_password_repair(text,text,text); drop function if exists public.app_save_phone(text,text);
create or replace function public.app_phone_valid(p_phone text) returns boolean language sql immutable as $$ select coalesce(p_phone,'') ~ '^[0-9]{2} [0-9]{5}-[0-9]{4}$'; $$;
create or replace function public.app_session_payload(p_member_id uuid,p_token text) returns jsonb language plpgsql security definer set search_path=public as $$ declare v_member public.blinders_members; begin select * into v_member from public.blinders_members where id=p_member_id; return jsonb_build_object('ok',true,'token',p_token,'member',jsonb_build_object('nick',v_member.nick,'iris',v_member.iris_id,'friendCode',v_member.friend_code,'role',v_member.role,'level',v_member.level),'balance',v_member.balance,'locked',v_member.locked,'vipPoints',v_member.vip_points); end; $$;
create or replace function public.app_login(p_login text,p_password text) returns jsonb language plpgsql security definer set search_path=public as $$ declare v_member public.blinders_members; v_token text; begin if coalesce(trim(p_login),'')='' or coalesce(p_password,'')='' then raise exception 'Preencha login e senha.'; end if; select * into v_member from public.blinders_members where lower(nick)=lower(trim(p_login)) or lower(iris_id)=lower(trim(p_login)) or lower(friend_code)=lower(trim(p_login)) limit 1; if v_member.id is null then raise exception 'Conta não encontrada.'; end if; if v_member.password_hash is null then raise exception 'Senha ainda não configurada. Use reparar senha.'; end if; if v_member.password_hash <> crypt(p_password,v_member.password_hash) then raise exception 'Senha inválida.'; end if; v_token:=encode(gen_random_bytes(32),'hex'); insert into public.blinders_sessions(token,member_id) values(v_token,v_member.id); return public.app_session_payload(v_member.id,v_token); end; $$;
create or replace function public.app_register(p_nick text,p_iris_id text,p_phone text,p_password text) returns jsonb language plpgsql security definer set search_path=public as $$ declare v_member_id uuid; v_token text; v_nick text:=trim(coalesce(p_nick,'')); v_iris text:=trim(coalesce(p_iris_id,'')); v_phone text:=trim(coalesce(p_phone,'')); begin if v_nick='' then raise exception 'Informe o nick.'; end if; if v_iris='' then raise exception 'Informe a conta IRIS/Zarcovi.'; end if; if length(coalesce(p_password,''))<4 then raise exception 'Senha muito curta.'; end if; if not public.app_phone_valid(v_phone) then raise exception 'Telefone inválido. Use xx xxxxx-xxxx.'; end if; if exists(select 1 from public.blinders_members where lower(nick)=lower(v_nick)) then raise exception 'Nick já cadastrado.'; end if; if exists(select 1 from public.blinders_members where lower(iris_id)=lower(v_iris)) then raise exception 'Conta IRIS/Zarcovi já cadastrada.'; end if; insert into public.blinders_members(nick,iris_id,phone,password_hash,balance,level,vip_points) values(v_nick,v_iris,v_phone,crypt(p_password,gen_salt('bf')),1000,1,0) returning id into v_member_id; update public.blinders_members set friend_code='FR-'||upper(substr(id::text,1,8)) where id=v_member_id; v_token:=encode(gen_random_bytes(32),'hex'); insert into public.blinders_sessions(token,member_id) values(v_token,v_member_id); return public.app_session_payload(v_member_id,v_token); end; $$;
create or replace function public.app_password_repair(p_login text,p_phone text,p_new_password text) returns jsonb language plpgsql security definer set search_path=public as $$ declare v_member public.blinders_members; begin if length(coalesce(p_new_password,''))<4 then raise exception 'Nova senha muito curta.'; end if; if not public.app_phone_valid(trim(coalesce(p_phone,''))) then raise exception 'Telefone inválido. Use xx xxxxx-xxxx.'; end if; select * into v_member from public.blinders_members where (lower(nick)=lower(trim(p_login)) or lower(iris_id)=lower(trim(p_login)) or lower(friend_code)=lower(trim(p_login))) and phone=trim(p_phone) limit 1; if v_member.id is null then raise exception 'Dados não conferem.'; end if; update public.blinders_members set password_hash=crypt(p_new_password,gen_salt('bf')),password_repaired_at=now() where id=v_member.id; return jsonb_build_object('ok',true,'message','Senha reparada.'); end; $$;
create or replace function public.app_save_phone(p_token text,p_phone text) returns jsonb language plpgsql security definer set search_path=public as $$ declare v_member uuid; begin if not public.app_phone_valid(trim(coalesce(p_phone,''))) then raise exception 'Telefone inválido. Use xx xxxxx-xxxx.'; end if; v_member:=public.app_current(p_token); update public.blinders_members set phone=trim(p_phone) where id=v_member; return jsonb_build_object('ok',true,'message','Telefone salvo.'); end; $$;
grant execute on function public.app_login(text,text) to anon,authenticated; grant execute on function public.app_register(text,text,text,text) to anon,authenticated; grant execute on function public.app_password_repair(text,text,text) to anon,authenticated; grant execute on function public.app_save_phone(text,text) to anon,authenticated;
notify pgrst,'reload schema'; select 'BLINDERS_RELEASE_V4_AUTH_SQL_OK' as status;
