const symbols=['CRYSTAL','SEVEN','CROWN','CARD','VAULT','CHIP']; const faces=['A','2','3','4','5','6','7','8','9','10','J','Q','K'];
export const games=[['roulette','Roulette','Roleta europeia com zero único.'],['blackjack','Blackjack','21, pedir carta, parar e banca.'],['bingo','Bingo','Cartela 1 a 100.'],['dice','Dice','Alto, baixo, par, ímpar e soma.'],['slots','Slots','Grade 3x3.'],['memory','Memory','Pares com até 3 erros.'],['crash','Crash','Multiplicador em tempo real.'],['poker','Poker','Mesa simples e 1x1.']];
export const rand=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;
export const drawCard=()=>faces[rand(0,faces.length-1)];
export function handValue(cards){let t=0,a=0;for(const c of cards){if(c==='A'){t+=11;a++}else if(['J','Q','K'].includes(c))t+=10;else t+=Number(c)}while(t>21&&a>0){t-=10;a--}return t}
function res(title,bet,mult,msg,visual){return{title,win:mult>0,multiplier:mult,payout:mult>0?bet*mult:0,message:`${msg} ${mult>0?`Pagamento ${mult}x.`:'Sem prêmio.'}`,visual}}
export function roulette(bet,choice){const number=rand(0,36),color=number===0?'green':number%2?'red':'black';let m=0;if(choice===color&&number!==0)m=2;else if(choice==='even'&&number!==0&&number%2===0)m=2;else if(choice==='odd'&&number%2===1)m=2;else if(/^\d+$/.test(choice)&&Number(choice)===number)m=36;return res('Roulette',bet,m,`Caiu ${number} ${color}.`,{number,color})}
export function dice(bet,choice){const d=[rand(1,6),rand(1,6)],total=d[0]+d[1];let m=0;if(choice==='high'&&total>=8)m=1.95;else if(choice==='low'&&total<=6)m=1.95;else if(choice==='even'&&total%2===0)m=1.95;else if(choice==='odd'&&total%2===1)m=1.95;else if(/^\d+$/.test(choice)&&Number(choice)===total)m=total===7?6:8;return res('Dice',bet,m,`Dados ${d[0]} + ${d[1]} = ${total}.`,{dice:d,total})}
export function slots(bet){const reel=Array.from({length:9},()=>symbols[rand(0,symbols.length-1)]);const lines=[[0,1,2],[3,4,5],[6,7,8],[0,4,8],[2,4,6]];let m=0;for(const line of lines){const [a,b,c]=line.map(i=>reel[i]);if(a===b&&b===c)m+=a==='SEVEN'?12:a==='CRYSTAL'?8:a==='CROWN'?6:4}return res('Slots',bet,m,m?`Linha vencedora ${m}x.`:'Sem linha vencedora.',{symbols:reel})}
export function blackjackFinish(bet,player,dealer){let pt=handValue(player),dt=handValue(dealer);while(dt<17){dealer.push(drawCard());dt=handValue(dealer)}const natural=player.length===2&&pt===21;let m=0;if(natural)m=2.5;else if(pt>21)m=0;else if(dt>21||pt>dt)m=2;else if(pt===dt)m=1;return res('Blackjack',bet,m,`Você ${pt} / Banca ${dt}.`,{player,dealer,playerTotal:pt,dealerTotal:dt})}
export function bingo(bet,picked){const pool=Array.from({length:100},(_,i)=>i+1),drawn=[];while(drawn.length<25)drawn.push(pool.splice(rand(0,pool.length-1),1)[0]);const clean=picked.filter(n=>Number.isInteger(n)&&n>=1&&n<=100).slice(0,10),hits=clean.filter(n=>drawn.includes(n)).length,m=hits>=10?25:hits>=8?12:hits>=6?5:hits>=4?2.5:hits>=3?1.5:0;return res('Bingo',bet,m,`${hits} acertos.`,{picked:clean,drawn,hits})}
export function memory(bet){const errors=rand(0,5),pairs=rand(3,8),m=errors<=3?Math.max(1.2,pairs/2):0;return res('Memory',bet,m,`${pairs} pares e ${errors} erros.`,{pairs,errors})}
export function crash(bet,target){const crashAt=+(1.05+Math.random()*7).toFixed(2),m=Number(target||2);return res('Crash',bet,m<crashAt?m:0,`Cashout ${m}x / Crash ${crashAt}x.`,{multiplier:m,crash:crashAt})}
export function poker(bet){const score=rand(1,100),m=score>95?10:score>84?4:score>68?2:0;return res('Poker',bet,m,m?`Mão vencedora ${m}x.`:'Mão sem prêmio.',{score,cards:[drawCard(),drawCard(),drawCard(),drawCard(),drawCard()]})}
