import { IrisSQL } from '../api/irisSql.js';
import { esc, oldMoney, parseMoney } from '../ui/format.js';
import { toast, musicPopup } from '../ui/toast.js';
import { games, roulette, dice, slots, drawCard, handValue, blackjackFinish, bingo, memory, crash, poker } from '../games/rules.js';
import { shopItems, territories, travelItems } from '../systems/catalog.js';
import { mountGameCanvas } from './Renderer.js';

const state={sqlConnected:false,member:{nick:'KageShinobi',iris:'IRIS-KAGE-777',friendCode:'KS-777',role:'admin',level:87},balance:25430.75,locked:0,vipPoints:12870,ranking:[['Shinigami_7',245780],['KageShinobi',189430],['AzulNeon',153920],['ShadowBR',99875],['IrisQueen',87610]],transactions:[],gameStatus:Object.fromEntries(games.map(g=>[g[0],{maintenance:false,live:true,duel:true}])),radio:{title:'',youtubeUrl:''},location:'vila_neon'};
let blackjackState=null;
export async function boot(){showLoading();updateLoading(35,'Sincronizando Banco IRIS');const remote=await IrisSQL.boot(state.member.nick);if(remote?.ok){applyRemote(remote);state.sqlConnected=true}else{state.sqlConnected=false;state.sqlMessage=remote?.error||'Banco IRIS indisponível.'}updateLoading(100,'Finalizando');await wait(160);hideLoading();setInterval(pollRadio,30000);pollRadio();}
export function route(){const app=document.querySelector('#app');if(!app)throw new Error('Elemento #app não encontrado.');const path=location.pathname||'/';const q=new URLSearchParams(location.search);if(path==='/'||path==='/home')return render(app,home());if(path==='/games')return render(app,gamesPage());if(path==='/game')return render(app,gamePage(q.get('game')||'roulette'));if(path==='/bank')return render(app,bankPage());if(path==='/shop')return render(app,shopPage());if(path==='/levels')return render(app,levelsPage());if(path==='/families')return render(app,familyPage('family'));if(path==='/mafias')return render(app,familyPage('mafia'));if(path==='/map')return render(app,mapPage());if(path==='/attacks')return render(app,attacksPage());if(path==='/travels')return render(app,travelsPage());if(path==='/marriage')return render(app,marriagePage());if(path==='/territory')return render(app,territoryPage());if(path==='/admin')return render(app,adminPage());return render(app,shell('Página não encontrada','<section class="panel">Rota não encontrada.</section>','home'))}
function render(app,html){app.innerHTML=html;bindLinks();bindActions();const canvas=document.querySelector('#pixiStage');if(canvas)mountGameCanvas(canvas,canvas.dataset.game||'default')}
function shell(title,body,active='home'){return `<main class="release-shell"><aside class="side"><a class="brand" href="/home"><img src="/assets/v14/icons/home.png"><b>BLINDERS</b><small>CASINO</small></a><nav class="menu-icons">${nav('/home','Home','home',active)}${nav('/games','Jogos','games',active)}${nav('/bank','Banco IRIS','bank',active)}${nav('/bank?action=transfer','Transferência','transfer',active)}${nav('/bank?action=deposit','Depósito','deposit',active)}${nav('/bank?action=withdraw','Saque','withdraw',active)}${nav('/levels','Leveis','levels',active)}${nav('/families','Famílias','families',active)}${nav('/mafias','Máfias','mafias',active)}${nav('/map','Mapa','map',active)}${nav('/attacks','Ataques','attacks',active)}${nav('/travels','Viagens','travels',active)}${nav('/marriage','Casamentos','marriage',active)}${nav('/territory','Território','territory',active)}${nav('/shop','Loja','shop',active)}${nav('/admin','Admin','admin',active)}</nav><section class="vip-panel"><img src="/assets/v14/items/coroa_vip.png"><b>DIAMANTE</b><span>${state.vipPoints.toLocaleString('pt-BR')} pts</span></section></aside><section class="main"><div class="top-ticker"><b>ANÚNCIO GLOBAL</b><span>Torneio Blackjack ao vivo • Rádio Blinders • Jogos 1x1 • Mapa e territórios ativos • Jackpot ${oldMoney(1458769.36)}</span></div><header class="topbar"><button data-menu>Menu</button><div>${esc(state.member.nick)} • Nível ${state.member.level||1} • Saldo ${oldMoney(state.balance)}</div><nav><button data-radio-toggle>Rádio</button><a href="/admin">Admin</a></nav></header><section class="hero"><h1>${esc(title)}</h1><p>${state.sqlConnected?'Banco IRIS online':'Banco IRIS indisponível'}</p></section>${body}<footer class="bottom-status"><span>Online agora 2.456</span><span>Jogadores hoje 12.364</span><span>Jackpot ${oldMoney(125347.89)}</span><span>Torneios ativos 3</span></footer></section></main><div id="toastStack" class="toast-stack"></div>`}
function nav(h,label,icon,active){return `<a class="${h.includes(active)||(active==='home'&&h==='/home')?'active':''}" href="${h}"><img src="/assets/v14/icons/${icon}.png"><span>${esc(label)}</span></a>`}
function home(){return shell('Blinders Cassino',`<section class="launch-grid"><article class="main-banner"><img src="/assets/v14/bg/lobby.png"><div><b>BLINDERS</b><span>O cassino de outro nível</span><a href="/games">Jogar agora</a></div></article><aside class="ranking"><h2>Ranking semanal</h2>${state.ranking.map((r,i)=>`<p><b>${i+1}. ${esc(r[0])}</b><span>${oldMoney(r[1])}</span></p>`).join('')}</aside><section class="game-strip">${games.map(g=>gameTile(g[0],g[1])).join('')}</section><article class="wallet-card"><img src="/assets/v14/bg/bank.png"><div><h2>Banco IRIS</h2><b>${oldMoney(state.balance)}</b><nav><a href="/bank?action=deposit">Depositar</a><a href="/bank?action=withdraw">Sacar</a><a href="/bank?action=transfer">Transferir</a></nav></div></article><article class="quick-transfer"><h2>Transferência entre membros</h2><input id="quickTo" value="Shinigami_7"><input id="quickAmount" value="10b"><button data-quick-transfer>Enviar transferência</button></article><article class="shop-mini"><h2>Itens & Loja</h2><div>${shopItems.slice(0,6).map(i=>`<img src="/assets/v14/items/${i[0]}.png" title="${esc(i[1])}">`).join('')}</div><a href="/shop">Ir para loja</a></article></section>`,'home')}
function gameTile(k,n){const st=state.gameStatus[k]||{};return `<a class="game-tile ${st.maintenance?'locked':''}" href="/game?game=${k}"><img src="/assets/v14/cards/${k}.png"><b>${esc(n)}</b><span>${st.maintenance?'Manutenção':'Jogar'}</span></a>`}
function gamesPage(){return shell('Jogos',`<section class="cards-grid">${games.map(g=>gameTile(g[0],g[1])).join('')}</section>`,'games')}
function gamePage(key){const g=games.find(x=>x[0]===key)||games[0],locked=state.gameStatus[key]?.maintenance;return shell(g[1],`<section class="game-screen game-${key}"><article class="game-table" style="background-image:linear-gradient(180deg,rgba(0,0,0,.2),rgba(0,0,0,.75)),url('/assets/v14/tables/${key}-table.png')"><div id="pixiStage" data-game="${key}" class="pixi-stage"></div><div id="gameVisual" class="game-visual">${gameVisual(key)}</div><div class="game-controls"><input id="bet" value="10b" ${locked?'disabled':''}>${choice(key)}${key==='blackjack'?`<button data-bj-start ${locked?'disabled':''}>Nova rodada</button><button data-bj-hit ${locked?'disabled':''}>Pedir carta</button><button data-bj-stop ${locked?'disabled':''}>Parar</button>`:`<button data-play="${key}" ${locked?'disabled':''}>Jogar</button>`}</div><p id="gameResult">${locked?'Este jogo está em manutenção.':'Pronto para jogar.'}</p></article></section>`,'games')}
function gameVisual(key){if(key==='blackjack')return `<div class="cards"><span>?</span><span>?</span></div><div class="cards"><span>?</span><span>?</span></div>`;if(key==='slots')return `<div class="slots">${Array.from({length:9},(_,i)=>`<span>${['7','C','V','R','A'][i%5]}</span>`).join('')}</div>`;if(key==='bingo')return `<div class="bingo">${Array.from({length:25},(_,i)=>`<span>${i+1}</span>`).join('')}</div>`;if(key==='dice')return `<div class="dice"><span>4</span><span>3</span></div>`;if(key==='crash')return `<div class="crash"><b>1.00x</b><canvas id="crashGraph" width="380" height="160"></canvas></div>`;return `<div class="roulette"><b>0</b></div>`}
function choice(key){if(key==='roulette')return `<select id="choice"><option value="red">Vermelho</option><option value="black">Preto</option><option value="even">Par</option><option value="odd">Ímpar</option><option value="7">Número 7</option></select>`;if(key==='dice')return `<select id="choice"><option value="high">Alto</option><option value="low">Baixo</option><option value="even">Par</option><option value="odd">Ímpar</option><option value="7">Soma 7</option></select>`;if(key==='bingo')return `<input id="choice" value="7,14,21,32,45,58,70,88,93,100">`;if(key==='crash')return `<input id="choice" value="2">`;return `<input id="choice" value="default">`}
function bankPage(){return shell('Banco IRIS',`<section class="bank-grid"><article class="balance-panel"><h2>Carteira</h2><b>${oldMoney(state.balance)}</b><span>Bloqueado ${oldMoney(state.locked)}</span></article><article><h2>Depósito</h2><input id="depositAmount" value="100b"><input id="depositRef" value="comprovante"><button data-bank="deposit">Registrar</button></article><article><h2>Saque</h2><input id="withdrawAmount" value="10b"><input id="withdrawDest" value="Conta Zarcovi"><button data-bank="withdraw">Solicitar</button></article><article><h2>Transferência</h2><input id="transferTo" value="Shinigami_7"><input id="transferAmount" value="10b"><button data-bank="transfer">Enviar</button></article><article class="history"><h2>Histórico</h2>${state.transactions.slice(0,20).map(t=>`<p><b>${esc(t.type)}</b><span>${oldMoney(t.amount)}</span><small>${esc(t.description||'')}</small></p>`).join('')||'Sem histórico'}</article></section>`,'bank')}
function shopPage(){return shell('Loja',`<section class="shop-grid">${shopItems.map(i=>`<article class="shop-card"><img src="/assets/v14/items/${i[0]}.png"><h2>${esc(i[1])}</h2><p>${esc(i[3])}</p><b>${oldMoney(i[2])}</b><button data-buy="${i[0]}">Comprar</button></article>`).join('')}</section>`,'shop')}
function levelsPage(){return shell('Leveis',`<section class="panel big"><h2>Nível ${state.member.level||1}</h2><p>Ganhe XP jogando, viajando, atacando territórios e participando de eventos.</p><div class="level-bar"><i style="width:64%"></i></div></section>`,'levels')}
function familyPage(kind){return shell(kind==='mafia'?'Máfias':'Famílias',`<section class="panel big"><h2>Criar ${kind==='mafia'?'Máfia':'Família'}</h2><input id="familyName" value="${kind==='mafia'?'Máfia Sombra':'Família Kage'}"><button data-create-family="${kind}">Criar</button></section>`,kind==='mafia'?'mafias':'families')}
function mapPage(){return shell('Mapa',`<section class="map-panel"><img src="/assets/v14/bg/map_world.png">${territories.map(t=>`<a href="/travels?to=${t[0]}" style="left:${8+t[2]/14}%;top:${18+t[3]/8}%"><img src="/assets/v14/map/${t[0]}.png"><span>${esc(t[1])}</span></a>`).join('')}</section>`,'map')}
function travelsPage(){return shell('Viagens',`<section class="cards-grid">${territories.map(t=>`<article class="shop-card"><img src="/assets/v14/map/${t[0]}.png"><h2>${esc(t[1])}</h2><p>Distância: ${Math.round(Math.hypot(t[2],t[3]))} km</p><select id="travelItem_${t[0]}"><option value="">Normal</option>${Object.keys(travelItems).map(k=>`<option value="${k}">${k}</option>`).join('')}</select><button data-travel="${t[0]}">Viajar</button></article>`).join('')}</section>`,'travels')}
function attacksPage(){return shell('Ataques',`<section class="cards-grid">${territories.map(t=>`<article class="shop-card"><img src="/assets/v14/map/${t[0]}.png"><h2>${esc(t[1])}</h2><button data-attack="${t[0]}">Atacar território</button></article>`).join('')}</section>`,'attacks')}
function marriagePage(){return shell('Casamentos',`<section class="panel big"><h2>Solicitar casamento</h2><input id="marryTarget" value="IrisQueen"><button data-marry>Enviar pedido</button></section>`,'marriage')}
function territoryPage(){return shell('Conquistas de território',`<section class="cards-grid">${territories.map(t=>`<article class="shop-card"><img src="/assets/v14/map/${t[0]}.png"><h2>${esc(t[1])}</h2><p>Dono atual: Livre</p></article>`).join('')}</section>`,'territory')}
function adminPage(){return shell('Admin',`<section class="admin-grid"><article><h2>Manutenção por jogo</h2>${games.map(g=>`<label><input type="checkbox" data-maint="${g[0]}" ${state.gameStatus[g[0]]?.maintenance?'checked':''}> ${esc(g[1])}</label>`).join('')}</article><article><h2>Rádio global YouTube</h2><input id="radioTitle" value="Rádio Blinders"><input id="radioUrl" placeholder="Link do YouTube"><button data-radio-save>Aplicar música global</button></article><article><h2>Alterar preço de item</h2><select id="priceItem">${shopItems.map(i=>`<option value="${i[0]}">${esc(i[1])}</option>`).join('')}</select><input id="priceValue" value="100b"><button data-price-save>Salvar preço</button></article><article><h2>Bônus admin</h2><input id="bonusAmount" value="100b"><button data-bonus>Aplicar bônus</button></article></section>`,'admin')}
function bindLinks(){document.querySelectorAll('a[href^="/"]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();history.pushState({},'',a.getAttribute('href'));route()}))}
function bindActions(){document.querySelector('[data-menu]')?.addEventListener('click',()=>document.body.classList.toggle('menu-open'));document.querySelector('[data-radio-toggle]')?.addEventListener('click',()=>toast(state.radio.title?`Rádio: ${state.radio.title}`:'Nenhuma rádio ativa.','warn'));document.querySelector('[data-quick-transfer]')?.addEventListener('click',()=>doTransfer('#quickTo','#quickAmount'));document.querySelector('[data-bank="transfer"]')?.addEventListener('click',()=>doTransfer('#transferTo','#transferAmount'));document.querySelector('[data-bank="deposit"]')?.addEventListener('click',()=>doBank('deposit'));document.querySelector('[data-bank="withdraw"]')?.addEventListener('click',()=>doBank('withdraw'));document.querySelector('[data-play]')?.addEventListener('click',e=>play(e.currentTarget.dataset.play));document.querySelector('[data-bj-start]')?.addEventListener('click',blackjackStart);document.querySelector('[data-bj-hit]')?.addEventListener('click',blackjackHit);document.querySelector('[data-bj-stop]')?.addEventListener('click',blackjackStop);document.querySelectorAll('[data-buy]').forEach(b=>b.addEventListener('click',()=>buy(b.dataset.buy)));document.querySelectorAll('[data-maint]').forEach(c=>c.addEventListener('change',()=>setMaintenance(c.dataset.maint,c.checked)));document.querySelector('[data-radio-save]')?.addEventListener('click',saveRadio);document.querySelector('[data-price-save]')?.addEventListener('click',savePrice);document.querySelector('[data-bonus]')?.addEventListener('click',bonus);document.querySelector('[data-create-family]')?.addEventListener('click',e=>createFamily(e.currentTarget.dataset.createFamily));document.querySelectorAll('[data-travel]').forEach(b=>b.addEventListener('click',()=>travel(b.dataset.travel)));document.querySelectorAll('[data-attack]').forEach(b=>b.addEventListener('click',()=>attack(b.dataset.attack)));document.querySelector('[data-marry]')?.addEventListener('click',marry)}
async function requireSql(action){if(!state.sqlConnected){toast('Banco IRIS indisponível. Ação real bloqueada.','bad');return null}const r=await action();if(!r?.ok){toast(r?.error||'Falha SQL.','bad');return null}return r}
async function doBank(type){const amount=parseMoney(document.querySelector(type==='deposit'?'#depositAmount':'#withdrawAmount')?.value),info=document.querySelector(type==='deposit'?'#depositRef':'#withdrawDest')?.value||'';const r=await requireSql(()=>type==='deposit'?IrisSQL.deposit(amount,info):IrisSQL.withdraw(amount,info));if(r)await refresh(type==='deposit'?'Depósito registrado.':'Saque solicitado.')}
async function doTransfer(toSel,amountSel){const to=document.querySelector(toSel)?.value||'',amount=parseMoney(document.querySelector(amountSel)?.value);const r=await requireSql(()=>IrisSQL.transfer(to,amount));if(r)await refresh('Transferência enviada.')}
async function play(key){const bet=parseMoney(document.querySelector('#bet')?.value),choice=document.querySelector('#choice')?.value||'default';let p;if(key==='roulette')p=roulette(bet,choice);else if(key==='dice')p=dice(bet,choice);else if(key==='slots')p=slots(bet);else if(key==='bingo')p=bingo(bet,choice.split(',').map(n=>Number(n.trim())));else if(key==='memory')p=memory(bet);else if(key==='crash')p=crash(bet,Number(choice));else if(key==='poker')p=poker(bet);else p=poker(bet);const r=await requireSql(()=>IrisSQL.playGame(key,bet,choice,p));if(r){applyRemote(r);showResult(p)}}
function blackjackStart(){const bet=parseMoney(document.querySelector('#bet')?.value);blackjackState={bet,player:[drawCard(),drawCard()],dealer:[drawCard(),drawCard()]};renderBj(`Total: ${handValue(blackjackState.player)}.`)}
function blackjackHit(){if(!blackjackState)return toast('Inicie rodada.','bad');blackjackState.player.push(drawCard());if(handValue(blackjackState.player)>21)blackjackStop();else renderBj(`Total: ${handValue(blackjackState.player)}.`)}
function renderBj(msg){document.querySelector('#gameVisual').innerHTML=`<div class="cards">${blackjackState.player.map(c=>`<span>${c}</span>`).join('')}</div><div class="cards"><span>${blackjackState.dealer[0]}</span><span>?</span></div>`;document.querySelector('#gameResult').textContent=msg}
async function blackjackStop(){if(!blackjackState)return;const p=blackjackFinish(blackjackState.bet,blackjackState.player,blackjackState.dealer),r=await requireSql(()=>IrisSQL.playGame('blackjack',blackjackState.bet,'stand',p));if(r){applyRemote(r);showResult(p)}blackjackState=null}
function showResult(p){document.querySelector('#gameResult').innerHTML=`${esc(p.message)}<br>Pagamento: ${oldMoney(p.payout)}`;toast(p.win?`Vitória ${oldMoney(p.payout)}`:'Rodada encerrada.',p.win?'good':'bad')}
async function buy(k){const r=await requireSql(()=>IrisSQL.buyItem(k));if(r)await refresh('Item comprado.')}
async function setMaintenance(g,l){const r=await requireSql(()=>IrisSQL.setGameMaintenance(g,l));if(r){state.gameStatus[g]={maintenance:l,live:!l};toast('Manutenção atualizada.','good')}}
async function saveRadio(){const t=document.querySelector('#radioTitle')?.value||'',u=document.querySelector('#radioUrl')?.value||'',r=await requireSql(()=>IrisSQL.setRadio(u,t));if(r){state.radio={title:t,youtubeUrl:u};musicPopup(t);toast('Rádio global atualizada.','good')}}
async function savePrice(){const key=document.querySelector('#priceItem')?.value,price=parseMoney(document.querySelector('#priceValue')?.value),r=await requireSql(()=>IrisSQL.setItemPrice(key,price));if(r)toast('Preço do item atualizado.','good')}
async function bonus(){const amount=parseMoney(document.querySelector('#bonusAmount')?.value),r=await requireSql(()=>IrisSQL.adminBonus(amount));if(r)await refresh('Bônus aplicado.')}
async function createFamily(k){const name=document.querySelector('#familyName')?.value||'',r=await requireSql(()=>IrisSQL.createFamily(name,k));if(r)toast(`${k==='mafia'?'Máfia':'Família'} criada.`,'good')}
async function travel(to){const item=document.querySelector(`#travelItem_${to}`)?.value||'',r=await requireSql(()=>IrisSQL.startTravel(to,item));if(r)toast(r.message||'Viagem iniciada.','good')}
async function attack(t){const r=await requireSql(()=>IrisSQL.attackTerritory(t));if(r)toast(r.message||'Ataque registrado.','good')}
async function marry(){const target=document.querySelector('#marryTarget')?.value||'',r=await requireSql(()=>IrisSQL.marry(target));if(r)toast('Pedido enviado.','good')}
async function refresh(msg){const r=await IrisSQL.wallet();if(r?.ok){applyRemote(r);toast(msg,'good');route()}}
function applyRemote(r){if(!r?.ok)return;state.sqlConnected=true;if(r.member)state.member={...state.member,...r.member};if(typeof r.balance==='number')state.balance=r.balance;if(typeof r.locked==='number')state.locked=r.locked;if(Array.isArray(r.transactions))state.transactions=r.transactions;if(Array.isArray(r.ranking))state.ranking=r.ranking.map(x=>[x.nick||x[0],Number(x.score||x[1]||0)]);if(r.gameStatus)state.gameStatus=r.gameStatus;if(r.radio)state.radio=r.radio}
async function pollRadio(){if(!state.sqlConnected)return;const r=await IrisSQL.getRadio();if(r?.ok&&r.radio?.title&&r.radio.title!==state.radio.title){state.radio=r.radio;musicPopup(r.radio.title)}}
function showLoading(){const e=document.createElement('div');e.id='loading';e.innerHTML='<section><b>BLINDERS</b><span id="loadingText">Carregando...</span><i><em id="loadingBar"></em></i></section>';document.body.appendChild(e)}
function updateLoading(p,t){const b=document.querySelector('#loadingBar');if(b)b.style.width=p+'%';const x=document.querySelector('#loadingText');if(x)x.textContent=t}
function hideLoading(){document.querySelector('#loading')?.remove()}
const wait=ms=>new Promise(r=>setTimeout(r,ms));
window.addEventListener('popstate',route);
