import { IrisSQL } from '../api/irisSql.js';

const state = { sqlConnected:false, sqlMessage:'Iniciando SQL...', member:{nick:'KageShinobi',iris:'IRIS-KAGE-777',friendCode:'KS-777'}, balance:0, locked:0, transactions:[], inventory:[], ranking:[] };
const games = [['roulette','Roulette'],['blackjack','Blackjack'],['bingo','Bingo'],['dice','Dice'],['slots','Slots'],['memory','Memory'],['crash','Crash'],['poker','Poker']];

export async function bootBlindersRuntime(){
  const remote = await IrisSQL.boot(state.member.nick);
  if(remote?.ok){ applyRemote(remote); state.sqlConnected=true; state.sqlMessage='Conectado ao Supabase SQL.'; }
  else { state.sqlConnected=false; state.sqlMessage=remote?.error||remote?.message||'Supabase não configurado.'; }
  window.BlindersRuntime = { sqlStatus:()=>IrisSQL.status(), sync: syncSql, state:()=>structuredClone(state) };
}

async function syncSql(){ const r=await IrisSQL.wallet(); if(r?.ok){applyRemote(r);state.sqlConnected=true;state.sqlMessage='Sincronizado com SQL.';route()} else toast(r?.error||'Falha SQL','bad'); return r; }

export function route(){
  const app=document.getElementById('app'); if(!app) throw new Error('Elemento #app não encontrado.');
  const path=location.pathname||'/'; const q=new URLSearchParams(location.search);
  if(path==='/'||path==='/menu') return render(app, menuPage());
  if(path==='/games') return render(app, gamesPage());
  if(path==='/game') return render(app, gamePage(q.get('game')||'roulette'));
  if(path==='/bank') return render(app, bankPage(q.get('action')||'overview'));
  if(path==='/shop') return render(app, shopPage());
  if(path==='/missions') return render(app, missionsPage());
  if(path==='/rankings') return render(app, rankingsPage());
  if(path==='/admin'||path==='/admin/command') return render(app, adminPage());
  return render(app, shell('Página não encontrada','<p>Rota não encontrada.</p>','menu'));
}

function render(app,html){ app.innerHTML=html; bindLinks(); bindActions(); }

function shell(title,body,active='menu'){ return `<main class="v14-shell"><aside class="v14-sidebar"><a class="v14-brand" href="/menu"><span class="brand-orb">B</span><span><b>BLINDERS</b><small>CASINO</small></span></a><nav class="v14-nav">${nav('/menu','Home',active==='menu')}${nav('/games','Jogos',active==='games')}${nav('/bank','Banco IRIS',active==='bank')}${nav('/bank?action=transfer','Transferências',active==='transfer')}${nav('/bank?action=deposit','Depósito',active==='deposit')}${nav('/bank?action=withdraw','Saque',active==='withdraw')}${nav('/shop','Loja',active==='shop')}${nav('/missions','Missões',active==='missions')}${nav('/rankings','Ranking',active==='rankings')}${nav('/admin/command','Admin',active==='admin')}</nav></aside><section class="v14-main"><div class="v14-ticker"><b>SQL</b><div><span>${esc(state.sqlMessage)} • Saldo ${money(state.balance)}</span></div></div><header class="v14-topbar"><div class="v14-search">${esc(state.member.nick)} • ${esc(state.member.iris)} • ${money(state.balance)}</div><nav><a href="/admin/command">Comando</a></nav></header><section class="v14-hero"><div><span class="project-signature">BLINDERS CASINO • IRIS SQL</span><h1>${esc(title)}</h1><p>${esc(state.sqlConnected?'Banco conectado':'Banco offline')}</p></div></section>${body}<footer class="v14-signature"><b>BLINDERS CASINO</b><span>${esc(state.sqlMessage)}</span></footer></section></main><div class="toast-stack" id="toastStack"></div>`; }
function nav(h,l,a){return `<a class="${a?'active':''}" href="${h}"><span class="nav-dot"></span><span>${esc(l)}</span></a>`;}

function menuPage(){ const tiles=games.map(g=>`<a class="v14-game-tile" href="/game?game=${g[0]}"><span>${esc(g[1])}</span><b>Jogar</b></a>`).join(''); return shell('Blinders Casino',`<section class="v14-dashboard"><article class="v14-main-banner"><div><span>BEM-VINDO AO</span><h2>BLINDERS</h2><p>Status: ${esc(state.sqlMessage)}</p><a class="primary-link" href="/games">Jogar agora</a></div></article><article class="v14-side-rank"><h2>Ranking semanal</h2><ol>${rankHtml()}</ol><a href="/rankings">Ver ranking</a></article><section class="v14-game-row">${tiles}</section><article class="v14-wallet-panel"><div><h2>Banco IRIS</h2><p>Saldo: <b>${money(state.balance)}</b></p><nav><a href="/bank?action=deposit">Depositar</a><a href="/bank?action=withdraw">Sacar</a><a href="/bank?action=transfer">Transferir</a></nav></div></article><article class="v14-shop-preview"><h2>Loja</h2><p>${state.inventory.length} itens</p><a href="/shop">Ir para loja</a></article></section>`,'menu'); }
function gamesPage(){ return shell('Jogos',`<section class="games-showcase-v14">${games.map(g=>`<article class="game-card-v14"><a href="/game?game=${g[0]}"><div class="game-card-v14-img"><span>${esc(g[1])}</span></div><div class="game-card-v14-body"><h2>${esc(g[1])}</h2><p>Jogo conectado ao SQL.</p><b>Jogar</b></div></a></article>`).join('')}</section>`,'games');}
function gamePage(game){ const info=games.find(g=>g[0]===game)||games[0]; return shell(info[1],`<section class="game-layout"><article class="game-stage-card"><div class="game-table-safe"><h2>${esc(info[1])}</h2><div id="gameDemo">${demo(game)}</div><div class="game-control-grid"><label>Aposta<input id="betAmount" value="150"></label><label>Escolha<input id="gameChoice" value="default"></label><button class="primary" data-play="${esc(game)}">Jogar SQL</button></div><div class="game-result" id="gameResult">Saldo: ${money(state.balance)}</div></div></article><aside class="game-side"><section class="panel"><h2>SQL</h2><p>${esc(state.sqlMessage)}</p></section></aside></section>`,'games');}
function bankPage(action){ const active=action==='overview'?'bank':action; return shell('Banco IRIS',`<section class="bank-layout"><article class="bank-card bank-hero-card"><h2>Carteira SQL</h2><b class="balance-demo">${money(state.balance)}</b><p>Bloqueado: ${money(state.locked)}</p></article><article class="bank-card"><h2>Depósito</h2><input id="depositAmount" value="1000"><input id="depositReference" value="Comprovante"><button class="primary" data-bank="deposit">Registrar depósito</button></article><article class="bank-card"><h2>Saque</h2><input id="withdrawAmount" value="500"><input id="withdrawDestination" value="Conta Zarcovi"><button class="primary" data-bank="withdraw">Solicitar saque</button></article><article class="bank-card"><h2>Transferência</h2><input id="transferTo" value="Shinigami_7"><input id="transferAmount" value="250"><button class="primary" data-bank="transfer">Enviar transferência</button></article><article class="bank-card bank-history-card"><h2>Histórico SQL</h2><div class="tx-list">${txHtml()}</div></article></section>`,active);}
function shopPage(){return shell('Loja',`<section class="admin-grid">${[['Moldura Neon',350],['Badge IRIS',500],['Título VIP',750],['Tema Anime Azul',900]].map(i=>`<article class="category-card"><h2>${esc(i[0])}</h2><b>${money(i[1])}</b><button class="primary" data-buy="${esc(i[0])}" data-price="${i[1]}">Comprar SQL</button></article>`).join('')}</section>`,'shop');}
function missionsPage(){return shell('Missões',`<section class="admin-grid">${[['Login diário',150],['Jogar 3 partidas',300],['Usar Banco IRIS',200]].map(i=>`<article class="category-card"><h2>${esc(i[0])}</h2><button class="primary" data-mission="${i[1]}" data-title="${esc(i[0])}">Coletar ${money(i[1])}</button></article>`).join('')}</section>`,'missions');}
function rankingsPage(){return shell('Ranking',`<section class="admin-grid">${(state.ranking||[]).map((r,i)=>`<article class="category-card"><h2>#${i+1} ${esc(r[0]||r.nick)}</h2><p>${money(r[1]||r.score||0)}</p></article>`).join('')}</section>`,'rankings');}
function adminPage(){return shell('Admin',`<section class="admin-grid"><article class="category-card"><h2>Status SQL</h2><p>${esc(state.sqlMessage)}</p><button class="primary" data-admin="sync">Sincronizar SQL</button></article><article class="category-card"><h2>Bônus</h2><button class="primary" data-admin="bonus">Aplicar bônus SQL</button></article></section>`,'admin');}

function bindLinks(){document.querySelectorAll('a[href^="/"]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();history.pushState({},'',a.getAttribute('href'));route();}));}
function bindActions(){ document.querySelector('[data-bank="deposit"]')?.addEventListener('click',()=>runSql(()=>IrisSQL.deposit(num('#depositAmount'),val('#depositReference')))); document.querySelector('[data-bank="withdraw"]')?.addEventListener('click',()=>runSql(()=>IrisSQL.withdraw(num('#withdrawAmount'),val('#withdrawDestination')))); document.querySelector('[data-bank="transfer"]')?.addEventListener('click',()=>runSql(()=>IrisSQL.transfer(val('#transferTo'),num('#transferAmount')))); document.querySelector('[data-play]')?.addEventListener('click',e=>runSql(()=>IrisSQL.playGame(e.currentTarget.dataset.play,num('#betAmount'),val('#gameChoice')),true)); document.querySelector('[data-buy]')?.addEventListener('click',e=>runSql(()=>IrisSQL.buyItem(e.currentTarget.dataset.buy,Number(e.currentTarget.dataset.price||0)))); document.querySelector('[data-mission]')?.addEventListener('click',e=>runSql(()=>IrisSQL.mission(Number(e.currentTarget.dataset.mission||0),e.currentTarget.dataset.title))); document.querySelector('[data-admin="sync"]')?.addEventListener('click',()=>syncSql()); document.querySelector('[data-admin="bonus"]')?.addEventListener('click',()=>runSql(()=>IrisSQL.adminBonus(777))); }
async function runSql(fn,isGame=false){ const res=await fn(); if(!res?.ok) return toast(res?.error||'Erro SQL. Rode o SQL no Supabase e recarregue.','bad'); applyRemote(res); toast(res.message||'SQL atualizado.','good'); if(isGame&&res.gameResult){const out=document.querySelector('#gameResult'); if(out) out.innerHTML=`${esc(res.gameResult.message||'Rodada SQL concluída.')}<br>Saldo: ${money(state.balance)}`;} else route();}
function applyRemote(remote){ if(!remote)return; state.sqlConnected=true; state.sqlMessage=remote.message||'Conectado ao SQL.'; if(remote.member) state.member={...state.member,nick:remote.member.nick||state.member.nick,iris:remote.member.iris||state.member.iris,friendCode:remote.member.friendCode||state.member.friendCode}; if(typeof remote.balance==='number')state.balance=remote.balance; if(typeof remote.locked==='number')state.locked=remote.locked; if(Array.isArray(remote.transactions))state.transactions=remote.transactions; if(Array.isArray(remote.inventory))state.inventory=remote.inventory; if(Array.isArray(remote.ranking))state.ranking=remote.ranking.map(x=>[x.nick||x[0],Number(x.score||x[1]||0)]);}
function txHtml(){return (state.transactions||[]).map(t=>`<div class="tx-row"><b>${esc(t.type)}</b><span>${money(t.amount)}</span><small>${esc(t.description||'')} • ${esc(t.status||'')}</small></div>`).join('')||'<p>Sem transações.</p>';}
function rankHtml(){return (state.ranking||[]).map(r=>`<li><b>${esc(r[0]||r.nick)}</b><span>${money(r[1]||r.score||0)}</span></li>`).join('')||'<li>Sem ranking</li>';}
function demo(game){if(game==='roulette')return'<div class="roulette-demo"><b>0</b></div>'; if(game==='dice')return'<div class="dice-demo"><span>4</span><span>3</span></div>'; return '<div class="generic-demo"><b>'+esc(game.toUpperCase())+'</b></div>';}
function val(sel){return document.querySelector(sel)?.value||'';} function num(sel){return Number(String(val(sel)).replace(',','.').replace(/[^0-9.]/g,''))||0;} function money(v){return 'R$ '+Number(v||0).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});}
function toast(msg,type=''){let s=document.querySelector('#toastStack');if(!s){s=document.createElement('div');s.id='toastStack';s.className='toast-stack';document.body.appendChild(s);}const e=document.createElement('div');e.className='toast '+type;e.textContent=msg;s.appendChild(e);requestAnimationFrame(()=>e.classList.add('show'));setTimeout(()=>{e.classList.remove('show');setTimeout(()=>e.remove(),300)},2600);}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
window.addEventListener('popstate',route);
